### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by rigu10** [bioidiap/spear#11]
Hi, i'm trying to install bob.ap using this buildout.cfg
```
[buildout]
parts = scripts
extensions = bob.buildout
prefer-final = false
eggs = bob.ap

debug = false
verbose = true
newest = false

[scripts]
recipe = bob.buildout:scripts
dependent-scripts = true
```

but when i execute 
    ./bin/buildout

i get this error

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 1712, in main
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 1700, in with_ei_usage
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 1716, in <lambda>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 211, in run
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 427, in easy_install
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 476, in install_item
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 655, in install_eggs
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 930, in build_and_install
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 919, in run_setup
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 62, in run_setup
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 105, in run
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 64, in <lambda>
  File "setup.py", line 74, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bob/extension/__init__.py", line 365, in __init__
    pkgs = check_packages(packages)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bob/extension/__init__.py", line 57, in check_packages
    p = pkgconfig(splitreq[0])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bob/extension/pkgconfig.py", line 131, in __init__
    raise RuntimeError("pkg-config package `%s' was not found" % name)
RuntimeError: pkg-config package `blitz' was not found
bob.buildout.extension: An error occurred when trying to install bob.blitz 2.0.6. Look above this message for any errors that were output by easy_install.
While:
  Installing scripts.
  Getting distribution for 'bob.ap'.
  Getting distribution for 'bob.blitz'.
Error: Couldn't install: bob.blitz 2.0.6

i tried to install blitz++, but nothing changed

**Comment by laurentes** [comment]
Hello,

The error message is quite explicit. The installation is looking for the pkg-config file from blitz++ but it hasn't managed to find it.

Which operating system are you using?
Do you use macports?
How did you install blitz++? 
Do you have such a file `/opt/local/lib/pkgconfig/blitz.pc`? You should.

**Comment by rigu10** [comment]
i'm under macosx 10.6
i installed blitz++ downloading it from [here](http://sourceforge.net/projects/blitz/) and exrcuitng ./configure,  make lib, make install

yes, i have macports

**Comment by anjos** [comment]
Just a small insertion here: avoid installing packages using different techniques. Uninstall the blitz package you installed manually and use **only the macports software**. Otherwise, it becomes very difficult to reproduce problems locally and help you.

Please note OS X 10.6 is not even supported anymore through MacPorts (https://www.macports.org). I'd advise an upgrade at least to Mountain Lion (10.8). If possible to Mavericks (10.9) or even Yosemite (10.10).
